### ISSUE TITLE
support of .net core

### ISSUE THREAD

**Issue by alexgubanow** [avmaisak/Gcode#24]
hi, are u planing to dropin an support for .net core?

**Comment by avmaisak** [comment]
yes, shure

**Comment by alexgubanow** [comment]
i would like to use your parser part in mine project. for now i just dropped in some files, to see the structure of project. https://github.com/alexgubanow/YaCB
I can try to help u with resolving issues to support .net core, if its needed.

**Comment by avmaisak** [comment]
@alexgubanow i just updated package to 0.2.10 version.

Updated to .NET  Standart 2.1
Tests updated to .NET Core 3

i normaly use with .net core 3 project
